spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:config/source_manager.db
    username: root
    password: root
  redis:
    cache:
      host: 127.0.0.1
      port: 6379
      password:
      lettuce:
        pool:
          max-active: 10
          max-wait: 60000
          max-idle: 5
          test-on-borrow: true