spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:config/source_manager.db
    username: root
    password: root
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3309/long_sms?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
#    max-active: 20
#    initial-size: 15
#    min-idle: 10
#    max-wait: 60000
#    username: root
#    password:
  redis:
    cache:
      host: 127.0.0.1
      port: 6379
      password:
      lettuce:
        pool:
          max-active: 10
          max-wait: 60000
          max-idle: 5
          test-on-borrow: true